import logging

# will disable all logging calls with levels less severe than or equal to CRITICAL while running unit-tests
logging.disable(logging.CRITICAL)

# will log all SQL statements generated by Peewee
# logger = logging.getLogger('peewee')
# logger.setLevel(logging.DEBUG)
# logger.addHandler(logging.StreamHandler())
