verbose_names = (
    "Cash & Short Term Investments",
    "Cash Only",
    "Short-Term Investments",
    "Cash & Short Term Investments Growth",
    "Cash & ST Investments / Total Assets",
    "Total Accounts Receivable",
    "Accounts Receivables, Net",
    "Accounts Receivables, Gross",
    "Bad Debt/Doubtful Accounts",
    "Other Receivables",
    "Accounts Receivable Growth",
    "Accounts Receivable Turnover",
    "Inventories",
    "Finished Goods",
    "Work in Progress",
    "Raw Materials",
    "Progress Payments & Other",
    "Other Current Assets",
    "Prepaid Expenses",
    "Miscellaneous Current Assets",
    "Total Current Assets",
    "Net Property, Plant & Equipment",
    "Property, Plant & Equipment - Gross",
    "Buildings",
    "Land & Improvements",
    "Machinery & Equipment",
    "Construction in Progress",
    "Leases",
    "Computer Software and Equipment",
    "Transportation Equipment",
    "Other Property, Plant & Equipment",
    "Accumulated Depreciation",
    "Buildings_2",
    "Land & Improvements_2",
    "Machinery & Equipment_2",
    "Construction in Progress_2",
    "Computer Software and Equipment_2",
    "Transportation Equipment_2",
    "Other Property, Plant & Equipment_2",
    "Total Investments and Advances",
    "LT Investment - Affiliate Companies",
    "Other Long-Term Investments",
    "Long-Term Note Receivable",
    "Intangible Assets",
    "Net Goodwill",
    "Net Other Intangibles",
    "Other Assets",
    "Deferred Charges",
    "Tangible Other Assets",
    "Total Assets",
    "Assets - Total - Growth",
    "Asset Turnover",
    "Return On Average Assets",
    "ST Debt & Current Portion LT Debt",
    "Short Term Debt",
    "Current Portion of Long Term Debt",
    "Accounts Payable",
    "Accounts Payable Growth",
    "Income Tax Payable",
    "Other Current Liabilities",
    "Miscellaneous Current Liabilities",
    "Total Current Liabilities",
    "Current Ratio",
    "Quick Ratio",
    "Cash Ratio",
    "Long-Term Debt",
    "Long-Term Debt excl. Capitalized Leases",
    "Non-Convertible Debt",
    "Convertible Debt",
    "Capitalized Lease Obligations",
    "Provision for Risks & Charges",
    "Deferred Taxes",
    "Deferred Taxes - Credit",
    "Deferred Taxes - Debit",
    "Other Liabilities",
    "Deferred Tax Liability-Untaxed Reserves",
    "Other Liabilities (excl. Deferred Income)",
    "Deferred Income",
    "Total Liabilities",
    "Non-Equity Reserves",
    "Total Liabilities / Total Assets",
    "Preferred Stock (Carrying Value)",
    "Redeemable Preferred Stock",
    "Non-Redeemable Preferred Stock",
    "Common Equity (Total)",
    "Common Stock Par/Carry Value",
    "Additional Paid-In Capital/Capital Surplus",
    "Retained Earnings",
    "ESOP Debt Guarantee",
    "Cumulative Translation Adjustment/Unrealized For. Exch. Gain",
    "Unrealized Gain/Loss Marketable Securities",
    "Revaluation Reserves",
    "Other Appropriated Reserves",
    "Unappropriated Reserves",
    "Treasury Stock",
    "Common Equity / Total Assets",
    "Total Shareholders' Equity",
    "Total Shareholders' Equity / Total Assets",
    "Accumulated Minority Interest",
    "Total Equity",
    "Liabilities & Shareholders' Equity",
)
