verbose_names = (
    "Net Income before Extraordinaries",
    "Net Income Growth",
    "Depreciation, Depletion & Amortization",
    "Depreciation and Depletion",
    "Amortization of Intangible Assets",
    "Deferred Taxes & Investment Tax Credit",
    "Investment Tax Credit",
    "Other Funds",
    "Funds from Operations",
    "Extraordinaries",
    "Changes in Working Capital",
    "Receivables",
    "Inventories",
    "Accounts Payable",
    "Income Taxes Payable",
    "Other Assets/Liabilities",
    "Net Operating Cash Flow",
    "Net Operating Cash Flow Growth",
    "Net Operating Cash Flow / Sales",
    "Capital Expenditures",
    "Capital Expenditures (Fixed Assets)",
    "Capital Expenditures (Other Assets)",
    "Capital Expenditures Growth",
    "Capital Expenditures / Sales",
    "Net Assets from Acquisitions",
    "Sale of Fixed Assets & Businesses",
    "Purchase/Sale of Investments",
    "Purchase of Investments",
    "Sale/Maturity of Investments",
    "Other Uses",
    "Other Sources",
    "Net Investing Cash Flow",
    "Net Investing Cash Flow Growth",
    "Net Investing Cash Flow / Sales",
    "Cash Dividends Paid - Total",
    "Common Dividends",
    "Preferred Dividends",
    "Change in Capital Stock",
    "Repurchase of Common & Preferred Stk.",
    "Sale of Common & Preferred Stock",
    "Proceeds from Stock Options",
    "Other Proceeds from Sale of Stock",
    "Issuance/Reduction of Debt, Net",
    "Change in Current Debt",
    "Change in Long-Term Debt",
    "Issuance of Long-Term Debt",
    "Reduction in Long-Term Debt",
    "Other Funds_2",
    "Other Uses_2",
    "Other Sources_2",
    "Net Financing Cash Flow",
    "Net Financing Cash Flow Growth",
    "Net Financing Cash Flow / Sales",
    "Exchange Rate Effect",
    "Miscellaneous Funds",
    "Net Change in Cash",
    "Free Cash Flow",
    "Free Cash Flow Growth",
    "Free Cash Flow Yield",
)
