verbose_names = (
    "Sales/Revenue",
    "Sales Growth",
    "Cost of Goods Sold (COGS) incl. D&A",
    "COGS excluding D&A",
    "Depreciation & Amortization Expense",
    "Depreciation",
    "Amortization of Intangibles",
    "Amortization of Deferred Charges",
    "COGS Growth",
    "Gross Income",
    "Gross Income Growth",
    "Gross Profit Margin",
    "SG&A Expense",
    "Research & Development",
    "Other SG&A",
    "SGA Growth",
    "Other Operating Expense",
    "Operating Income",
    "Unusual Expense",
    "EBIT Growth",
    "EBIT Margin",
    "Non Operating Income/Expense",
    "Non-Operating Interest Income",
    "Equity in Affiliates (Pretax)",
    "Interest Expense",
    "Interest Expense Growth",
    "Gross Interest Expense",
    "Interest Capitalized",
    "Pretax Income",
    "Pretax Income Growth",
    "Pretax Margin",
    "Income Tax",
    "Income Tax - Current Domestic",
    "Income Tax - Current Foreign",
    "Income Tax - Deferred Domestic",
    "Income Tax - Deferred Foreign",
    "Income Tax Credits",
    "Equity in Affiliates",
    "Other After Tax Income (Expense)",
    "Consolidated Net Income",
    "Minority Interest Expense",
    "Net Income",
    "Net Income Growth",
    "Net Margin",
    "Extraordinaries & Discontinued Operations",
    "Extra Items & Gain/Loss Sale Of Assets",
    "Cumulative Effect - Accounting Chg",
    "Discontinued Operations",
    "Net Income After Extraordinaries",
    "Preferred Dividends",
    "Net Income Available to Common",
    "EPS (Basic)",
    "EPS (Basic) Growth",
    "Basic Shares Outstanding",
    "EPS (Diluted)",
    "EPS (Diluted) Growth",
    "Diluted Shares Outstanding",
    "EBITDA",
    "EBITDA Growth",
    "EBITDA Margin",
)
